"""
config.py
---------
Central place for filesystem paths used across the project, so no other
module hardcodes paths individually.
"""

import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Datasets
DATASETS_DIR = os.path.join(PROJECT_ROOT, "datasets")
RESUME_DATASET_PATH = os.path.join(DATASETS_DIR, "resume_dataset.csv")
SKILLS_DB_PATH = os.path.join(DATASETS_DIR, "skills_database.json")
RESUME_RULES_PATH = os.path.join(DATASETS_DIR, "resume_rules.json")
SAMPLE_JD_DIR = os.path.join(DATASETS_DIR, "sample_job_descriptions")

# Model artifacts
MODELS_DIR = os.path.join(PROJECT_ROOT, "models")
MODEL_PATH = os.path.join(MODELS_DIR, "saved_model.keras")
TOKENIZER_PATH = os.path.join(MODELS_DIR, "tokenizer.pkl")
LABEL_ENCODERS_PATH = os.path.join(MODELS_DIR, "label_encoders.pkl")
EVALUATION_REPORT_PATH = os.path.join(MODELS_DIR, "evaluation_report.json")

# Output reports (generated by the Streamlit app)
REPORTS_DIR = os.path.join(PROJECT_ROOT, "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)
